-- Generated by nwg-displays on 2026-06-22 at 18:33:47. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",	
    persistent = true
})
