[accessibility]
ui_scale = 1.1000000089406967

[bar]
order = [ "Top" ]

    [bar.Top]
    background_opacity = 0.4999999888241291
    capsule = true
    capsule_opacity = 0.84999998100101948
    capsule_padding = 12.0
    center = [ "taskbar" ]
    contact_shadow = true
    end = [
        "tray",
        "indicator",
        "control-center",
        "notifications",
        "network",
        "bluetooth",
        "volume",
        "ram",
        "battery",
        "brightness",
        "clock"
    ]
    margin_ends = 0
    radius = 0
    radius_bottom_left = 14
    radius_bottom_right = 14
    scale = 1.1000000089406967
    start = [ "launcher", "Launcher", "wallpaper", "workspaces", "media", "gamermode" ]
    thickness = 36

[control_center]
hidden_tabs = [ "screen-time" ]

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1371.199951171875
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bands = 32
        show_when_idle = true

[dock]
active_monitor_only = true
background_opacity = 0.0
border = "on_secondary"
icon_size = 42
launcher_icon = "layout-list-filled"
magnification = false
radius = 18
shadow = false

[location]
auto_locate = true

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 540.0
    cy = 1801.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

[notification]
background_opacity = 0.89999997988343239
monitors = [ "HDMI-A-1" ]
position = "top_center"
show_app_name = false

[osd]
background_opacity = 0.69999998435378075
scale = 0.85000000521540642

    [osd.kinds]
    volume_input = false

[plugin_settings."noctalia/wallhaven"]
api_key = "9EEukPARQOOUdcidKs1tzZCPcyRsm645"
browser_open_near_click = true
download_dir = "/home/bypass/.local/share/wallpapers/"

[plugin_settings."nomadcxx/gamer-mode"]
main_placement = "floating"
main_position = "center"

[plugins]
enabled = [ "nomadcxx/gamer-mode", "rxtsel/portctl" ]

[shell]
app_icon_color = "hover"
app_icon_colorize = true
avatar_path = "/home/bypass/.user_image"
clipboard_enabled = false
corner_radius_scale = 1.3500000201165676
font_family = "Space Grotesk Bold"
panel_anchor_bar = "Top"
time_format = "{:%hh:%M}"

    [shell.animation]
    speed = 1.2000000178813934

    [shell.launcher]
    categories = false

    [shell.panel]
    control_center_placement = "floating"
    launcher_placement = "attached"
    open_near_click_control_center = true

[theme]
builtin = "Noctalia"
community_palette = "Monochrome"
custom_palette = "bepi"
mode = "dark"
source = "custom"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    community_ids = [ "hyprtoolkit" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/home/bypass/Pictures/Wallpapers/wallhaven-21kgq9.png"

    [wallpaper.last]
    path = "/home/bypass/Pictures/Wallpapers/wallhaven-21kgq9.png"

    [wallpaper.monitors.DP-1]
    path = "/home/bypass/Pictures/Wallpapers/wallhaven-21kgq9.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/bypass/Pictures/Wallpapers/wallhaven-21kgq9.png"

    [[wallpaper.favorite]]
    path = "/home/bypass/Pictures/Wallpapers/poy1zj.png"
    theme_mode = "auto"

[weather]
unit = "imperial"

[widget.Launcher]
custom_image = "/home/zikuu/Documents/logo_new.png"
type = "custom_button"

    [widget.Launcher.actions]
    left = "exec vicinae toggle"
    middle = "none"
    right = "exec vicinae vicinae://launch/wm/switch-windows"

[widget.clock]
format = "{:%-I:%M %p}"
scale = 1.1000000000000001

[widget.control-center]
enabled = false
glyph = "layout-navbar-filled"

[widget.gamermode]
type = "nomadcxx/gamer-mode:gamermode"

[widget.indicator]
enabled = false
type = "rxtsel/portctl:indicator"

[widget.launcher]
custom_image = "/home/bypass/Documents/Downloads-07.18.2026/c30_empty_w.png"
custom_image_colorize = true
enabled = false

[widget.media]
enabled = false

[widget.network]
show_label = false

[widget.taskbar]
enabled = false

[widget.tray]
color = "hover"
icon_color = "hover"

[widget.wallpaper]
enabled = false

[widget.workspaces]
active_pill_size = 2.5500000000000003
